-- 0-10%
INSERT INTO brands (brand_name, overall_score) VALUES
('Reliance Trends', 10),
('Costco', 10),
('Tommy Bahama', 10),
('Saks Fifth Avenue', 9),
('Foot Locker', 9),
('Famous Footwear', 9),
('Tod’s', 9),
('Li-Ning', 9),
('Hudson’s Bay', 9),
('LL Bean', 8),
('Gerry Weber', 8),
('Merrell', 8),
('AJIO', 8),
('Carhartt', 7),
('Truworths', 7),
('Triumph', 7),
('Takko', 7),
('Sports Direct', 7),
('DSW', 7),
('Beanpole', 7),
('Bloomingdale’s', 7),
('Macy’s', 7),
('SHEIN', 7),
('Skechers', 6),
('Kmart', 6),
('Billabong', 6),
('Quiksilver', 6),
('Roxy', 6),
('Ross Dress for Less', 6),
('Express', 5),
('Furla', 5),
('Eddie Bauer', 5),
('CAROLL', 4),
('Buckle', 4),
('Shimamura', 4),
('LC Waikiki', 3),
('Dillard’s', 3),
('Aeropostale', 3),
('Romwe', 2),
('Longchamp', 2),
('Pepe Jeans', 2),
('Deichmann', 2),
('Jockey', 2),
('Dolce & Gabbana', 2),
('REVOLVE', 1),
('Fabletics', 1),
('BCBGMAXAZRIA', 1),
('Reebok', 1),
('Max', 1),
('celio', 1),
('DKNY', 0),
('Nine West', 0),
('Tory Burch', 0),
('Splash', 0),
('Fashion Nova', 0),
('Max Mara', 0),
('New Yorker', 0),
('Tom Ford', 0),
('ANTA', 0),
('Bosideng', 0),
('Heilan Home', 0),
('Belle', 0),
('Big Bazaar – ffb', 0),
('Semir', 0),
('Van Heusen', 0),
('K-Way', 0),
('KOOVS', 0),
('Metersbonwe', 0),
('Mexx', 0),
('Savage X Fenty', 0),
('Youngor', 0);

-- 11-20%
INSERT INTO brands (brand_name, overall_score) VALUES
('Reserved', 20),
('Otto', 20),
('Diesel', 19),
('Victoria’s Secret', 19),
('Pimkie', 18),
('Foschini', 18),
('Mizuno', 18),
('Joe Fresh', 18),
('Fanatics', 18),
('Jil Sander', 18),
('Monoprix', 18),
('Valentino', 18),
('The Warehouse', 17),
('Clarks', 17),
('Marni', 17),
('The Children’s Place', 17),
('Kohl’s', 17),
('KiK', 17),
('United Arrows', 17),
('Kiabi', 16),
('Fossil', 16),
('Carolina Herrera', 16),
('Canada Goose', 16),
('Fila', 15),
('Burlington', 14),
('ALDO', 14),
('Brunello Cucinelli', 14),
('Chico’s', 14),
('TOPVALU COLLECTION', 13),
('TJ Maxx', 13),
('Anthropologie', 13),
('Free People', 13),
('Urban Outfitters', 13),
('Steve Madden', 13),
('La Redoute', 12),
('Lands’ End', 12),
('Kaufland', 11),
('Ito-Yokado', 11),
('MRP', 11),
('Falabella', 11),
('Chanel', 11);

-- 21-30%
INSERT INTO brands (brand_name, overall_score) VALUES
('Helly Hansen', 30),
('CELINE', 30),
('JD Sports', 29),
('Matalan', 29),
('Woolworths South Africa', 29),
('Dior', 29),
('Kathmandu', 29),
('Louis Vuitton', 29),
('Morrisons', 29),
('Marc Jacobs', 28),
('Muji', 28),
('Asda', 28),
('Hermès', 28),
('Under Armour', 28),
('Dick’s Sporting Goods', 27),
('Very', 27),
('Gymshark', 27),
('Moncler', 27),
('Nordstrom', 26),
('Decathlon', 26),
('Ted Baker', 26),
('Amazon', 26),
('Lidl', 25),
('Paris', 25),
('Desigual', 25),
('Jack Wolfskin', 25),
('Carter’s', 25),
('boohoo', 24),
('PrettyLittleThing', 24),
('Salvatore Ferragamo', 24),
('El Corte Inglés', 24),
('HEMA', 24),
('Carrefour', 24),
('Versace', 23),
('Michael Kors', 23),
('Walmart', 22),
('Prisma', 22),
('Disney', 22),
('Cotton On', 22),
('Aritzia', 22),
('Sandro', 22),
('REI', 21),
('American Eagle', 21),
('Cortefiel', 21);

-- 31-40%
INSERT INTO brands (brand_name, overall_score) VALUES
('Fjällräven', 40),
('Zalando', 40),
('Patagonia', 40),
('Primark', 40),
('Big W', 39),
('Armani', 38),
('Burberry', 38),
('Marks & Spencer', 38),
('Champion', 38),
('Lacoste', 38),
('Hanes', 37),
('Bonprix', 37),
('Target', 37),
('Columbia Sportswear', 36),
('Next', 36),
('Brooks Sport', 35),
('Dr. Martens', 35),
('Mammut', 34),
('ALDI SOUTH', 34),
('Miu Miu', 34),
('Prada', 34),
('Fruit of the Loom', 34),
('Russell Athletic', 33),
('Abercrombie & Fitch', 33),
('Hollister Co.', 33),
('Bally', 33),
('Wrangler', 33),
('Ermenegildo Zegna', 32),
('John Lewis', 32),
('River Island', 31),
('ALDI Nord', 31),
('GUESS', 31);

-- 41-50%
INSERT INTO brands (brand_name, overall_score) VALUES
('Tom Tailor', 50),
('ASOS', 50),
('Converse', 50),
('Jordan', 50),
('Nike', 50),
('Bershka', 50),
('Massimo Dutti', 50),
('Pull&Bear', 50),
('Stradivarius', 50),
('Zara', 50),
('Tommy Hilfiger', 50),
('G-Star RAW', 49),
('Mango', 49),
('Superdry', 49),
('Banana Republic', 48),
('Gap', 48),
('Old Navy', 48),
('Calvin Klein', 48),
('Tesco', 48),
('Speedo', 47),
('New Balance', 46),
('ASICS', 45),
('Esprit', 45),
('Lindex', 44),
('Chloé', 43),
('Tchibo', 43),
('s.Oliver', 43),
('New Look', 42),
('COACH', 42),
('Jack & Jones', 41),
('Vero Moda', 41),
('Kate Spade', 41);

-- 51-60%
INSERT INTO brands (brand_name, overall_score) VALUES
('Levi Strauss & Co', 60),
('Fendi', 58),
('UGG', 57),
('Adidas', 56),
('Hugo Boss', 55),
('Ralph Lauren', 54),
('Zeeman', 54),
('Gildan', 54),
('Lululemon', 52),
('Sainsbury’s', 51),
('Balenciaga', 51),
('Bottega Veneta', 51),
('SAINT LAURENT', 51),
('GU', 51),
('Uniqlo', 51);

-- 61-70%
INSERT INTO brands (brand_name, overall_score) VALUES
('C&A', 68),
('Puma', 66),
('The North Face', 66),
('Timberland', 66),
('Vans', 65),
('Dressmann', 65),
('Calzedonia', 63),
('Intimissimi', 63),
('Tezenis', 63);

-- 71-80%
INSERT INTO brands (brand_name, overall_score) VALUES
('Gucci', 80),
('Kmart Australia', 76),
('Target Australia', 76),
('United Colors of Benetton', 73),
('H&M', 71);

-- 81-90%
INSERT INTO brands (brand_name, overall_score) VALUES
('OVS', 83);

-- 91-100%
-- lol got nothing here